# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Python\MXP_Rename\MXP_Rename_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(402, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 4)
        self.Start_Rename = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_Rename.sizePolicy().hasHeightForWidth())
        self.Start_Rename.setSizePolicy(sizePolicy)
        self.Start_Rename.setMinimumSize(QtCore.QSize(100, 30))
        self.Start_Rename.setObjectName("Start_Rename")
        self.gridLayout.addWidget(self.Start_Rename, 7, 1, 1, 1)
        self.Path = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Path.sizePolicy().hasHeightForWidth())
        self.Path.setSizePolicy(sizePolicy)
        self.Path.setMinimumSize(QtCore.QSize(0, 25))
        self.Path.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Path.setObjectName("Path")
        self.gridLayout.addWidget(self.Path, 0, 1, 1, 3)
        self.Path_choose = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Path_choose.sizePolicy().hasHeightForWidth())
        self.Path_choose.setSizePolicy(sizePolicy)
        self.Path_choose.setMinimumSize(QtCore.QSize(25, 25))
        self.Path_choose.setMaximumSize(QtCore.QSize(30, 25))
        self.Path_choose.setObjectName("Path_choose")
        self.gridLayout.addWidget(self.Path_choose, 0, 4, 1, 1)
        self.Gauge_file_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gauge_file_label.sizePolicy().hasHeightForWidth())
        self.Gauge_file_label.setSizePolicy(sizePolicy)
        self.Gauge_file_label.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Gauge_file_label.setFont(font)
        self.Gauge_file_label.setObjectName("Gauge_file_label")
        self.gridLayout.addWidget(self.Gauge_file_label, 1, 0, 1, 1)
        self.Die_Count_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Die_Count_label.sizePolicy().hasHeightForWidth())
        self.Die_Count_label.setSizePolicy(sizePolicy)
        self.Die_Count_label.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Die_Count_label.setFont(font)
        self.Die_Count_label.setObjectName("Die_Count_label")
        self.gridLayout.addWidget(self.Die_Count_label, 5, 0, 1, 1)
        self.Die_Count = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Die_Count.sizePolicy().hasHeightForWidth())
        self.Die_Count.setSizePolicy(sizePolicy)
        self.Die_Count.setMinimumSize(QtCore.QSize(0, 25))
        self.Die_Count.setMaximumSize(QtCore.QSize(60, 25))
        self.Die_Count.setObjectName("Die_Count")
        self.gridLayout.addWidget(self.Die_Count, 5, 1, 1, 1)
        self.HS_Count_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HS_Count_label.sizePolicy().hasHeightForWidth())
        self.HS_Count_label.setSizePolicy(sizePolicy)
        self.HS_Count_label.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HS_Count_label.setFont(font)
        self.HS_Count_label.setObjectName("HS_Count_label")
        self.gridLayout.addWidget(self.HS_Count_label, 2, 0, 1, 1)
        self.HS_Count = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HS_Count.sizePolicy().hasHeightForWidth())
        self.HS_Count.setSizePolicy(sizePolicy)
        self.HS_Count.setMinimumSize(QtCore.QSize(0, 25))
        self.HS_Count.setMaximumSize(QtCore.QSize(60, 25))
        self.HS_Count.setObjectName("HS_Count")
        self.gridLayout.addWidget(self.HS_Count, 2, 1, 1, 1)
        self.Gauge_choose = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gauge_choose.sizePolicy().hasHeightForWidth())
        self.Gauge_choose.setSizePolicy(sizePolicy)
        self.Gauge_choose.setMinimumSize(QtCore.QSize(25, 25))
        self.Gauge_choose.setMaximumSize(QtCore.QSize(30, 25))
        self.Gauge_choose.setObjectName("Gauge_choose")
        self.gridLayout.addWidget(self.Gauge_choose, 1, 4, 1, 1)
        self.Gauge = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gauge.sizePolicy().hasHeightForWidth())
        self.Gauge.setSizePolicy(sizePolicy)
        self.Gauge.setMinimumSize(QtCore.QSize(0, 25))
        self.Gauge.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Gauge.setObjectName("Gauge")
        self.gridLayout.addWidget(self.Gauge, 1, 1, 1, 3)
        self.Path_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Path_label.sizePolicy().hasHeightForWidth())
        self.Path_label.setSizePolicy(sizePolicy)
        self.Path_label.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Path_label.setFont(font)
        self.Path_label.setObjectName("Path_label")
        self.gridLayout.addWidget(self.Path_label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(400, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Start_Rename.clicked.connect(self.start_onclick)
        self.Path_choose.clicked.connect(self.path_choose_onclick)
        self.Gauge_choose.clicked.connect(self.gauge_choose_onclick)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MXP Rename"))
        MainWindow.setToolTip(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "(If leave blank, software will calculate Die count based on second sheet in given gauge Excel file)"))
        self.Start_Rename.setText(_translate("MainWindow", "Start Rename"))
        self.Path_choose.setToolTip(_translate("MainWindow", "Click to choose folder"))
        self.Path_choose.setText(_translate("MainWindow", "..."))
        self.Gauge_file_label.setText(_translate("MainWindow", "Please choose your gauge file here:"))
        self.Die_Count_label.setText(_translate("MainWindow", "Please enter Die count here:"))
        self.HS_Count_label.setText(_translate("MainWindow", "Please enter HS count here:"))
        self.Gauge_choose.setToolTip(_translate("MainWindow", "Click to choose gauge file"))
        self.Gauge_choose.setText(_translate("MainWindow", "..."))
        self.Path_label.setText(_translate("MainWindow", "Please choose your path here:"))
        self.label.setText(_translate("MainWindow", "(If leave blank, software will calculate HS count based on first sheet in given gauge Excel file)"))

