# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Python\PitchWalking_GUI\PitchWalking_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, sip

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.radioButton_forX = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_forX.setChecked(True)
        self.radioButton_forX.setObjectName("radioButton_forX")
        self.gridLayout.addWidget(self.radioButton_forX, 4, 1, 1, 1)
        self.pushButton_forStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_forStart.setObjectName("pushButton_forStart")
        self.gridLayout.addWidget(self.pushButton_forStart, 5, 1, 1, 1)
        self.shrink_px = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shrink_px.sizePolicy().hasHeightForWidth())
        self.shrink_px.setSizePolicy(sizePolicy)
        self.shrink_px.setMaximumSize(QtCore.QSize(75, 25))
        self.shrink_px.setObjectName("shrink_px")
        self.gridLayout.addWidget(self.shrink_px, 2, 1, 1, 1)
        self.lower_limit = QtWidgets.QTextEdit(self.centralwidget)
        self.lower_limit.setMaximumSize(QtCore.QSize(75, 25))
        self.lower_limit.setObjectName("lower_limit")
        self.gridLayout.addWidget(self.lower_limit, 3, 2, 1, 1)
        self.radioButton_forY = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_forY.setObjectName("radioButton_forY")
        self.gridLayout.addWidget(self.radioButton_forY, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.upper_limit = QtWidgets.QTextEdit(self.centralwidget)
        self.upper_limit.setMaximumSize(QtCore.QSize(75, 25))
        self.upper_limit.setObjectName("upper_limit")
        self.gridLayout.addWidget(self.upper_limit, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.customized_range = QtWidgets.QTextEdit(self.centralwidget)
        self.customized_range.setMaximumSize(QtCore.QSize(75, 25))
        self.customized_range.setObjectName("customized_range")
        self.gridLayout.addWidget(self.customized_range, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 3)
        self.SearchPath = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchPath.sizePolicy().hasHeightForWidth())
        self.SearchPath.setSizePolicy(sizePolicy)
        self.SearchPath.setMinimumSize(QtCore.QSize(200, 0))
        self.SearchPath.setMaximumSize(QtCore.QSize(750, 25))
        self.SearchPath.setObjectName("SearchPath")
        self.gridLayout.addWidget(self.SearchPath, 0, 1, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_forStart.clicked.connect(self.on_click)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pitch Walking"))
        self.label.setText(_translate("MainWindow", "Please enter path here"))
        self.label_2.setText(_translate("MainWindow", "Please enter pixel for shrink"))
        self.label_4.setText(_translate("MainWindow", "Please enter CD limit"))
        self.label_3.setText(_translate("MainWindow", "Please select direction"))
        self.radioButton_forX.setText(_translate("MainWindow", "X"))
        self.pushButton_forStart.setText(_translate("MainWindow", "Start"))
        self.radioButton_forY.setText(_translate("MainWindow", "Y"))
        self.label_6.setText(_translate("MainWindow", "Upper Limit (nm)"))
        self.label_5.setText(_translate("MainWindow", "Lower limit (nm)"))
        self.label_7.setText(_translate("MainWindow", "Please enter desired pixel range"))
        self.label_8.setText(_translate("MainWindow", "(i.e. CD value within how many pixels will be considered as one column)"))
        self.label_9.setText(_translate("MainWindow", "(i.e. H bar in this range from edges will be ingored)"))

